name: first workflow

on:
  workflow_dispatch:
  
jobs:
  firstjob:
    runs-on: self-hosted
    steps:
      - name: firstJob script
        shell: cmd
        run: echo Hello World! This is the first job
        
  seconjob:
    runs-on: ubuntu-latest
    steps:
      - name: secondJob script
        shell: bash
        run: |
          echo this is the second
          echo and this is a multi-line script
    
